<?php

return [
    [['GET', 'POST'], '/adminconsole', ['Controllers\ConsoleController', 'display']],
    [['GET', 'POST'], '/report/{name}/{format}', ['Controllers\ReportController', 'display']],
    [['GET', 'POST'], '/officer', ['Controllers\OfficerPaymentController', 'display']],
    [['GET', 'POST'], '/password', ['Controllers\PasswordController', 'display']],
    [['GET', 'POST'], '/employee/create', ['Controllers\EmployeeCreateController', 'display']],
    [['GET', 'POST'], '/employee/edit', ['Controllers\EmployeeEditController', 'display']],
    [['GET', 'POST'], '/employee/view', ['Controllers\EmployeeViewController', 'display']],
    [['GET', 'POST'], '/employee/deactivate', ['Controllers\EmployeeDeactivateController', 'display']],
    [['GET', 'POST'], '/company/create', ['Controllers\CompanyCreateController', 'display']],
    [['GET', 'POST'], '/company/edit', ['Controllers\CompanyEditController', 'display']],
    [['GET', 'POST'], '/company/deactivate', ['Controllers\CompanyDeactivateController', 'display']],
    [['GET', 'POST'], '/admin/createuser', ['Controllers\CreateAdminUserController', 'display']],
    [['GET', 'POST'], '/admin/edituser', ['Controllers\EditAdminUserController', 'display']],
    [['GET', 'POST'], '/admin/managetravel', ['Controllers\ManageTravelController', 'display']],
    [['GET', 'POST'], '/admin/managepot', ['Controllers\ManagePOTController', 'display']],
    [['GET', 'POST'], '/admin/manageother', ['Controllers\ManageOtherController', 'display']],
    [['GET', 'POST'], '/createpayment', ['Controllers\MakePaymentController', 'display']],
    [['GET', 'POST'], '/editpayment', ['Controllers\EditPaymentController', 'display']],
    [['GET', 'POST'], '/amendpayment', ['Controllers\AmendPaymentController', 'display']],
    [['GET', 'POST'], '/admin/processpayroll', ['Controllers\PayrollController', 'display']],
    [['GET', 'POST'], '/tablepymt', ['Controllers\PaymentTableController', 'display']],
    [['GET', 'POST'], '/success', ['Controllers\SuccessController', 'display']],
    [['GET'], '/unlockpymt', ['Controllers\PaymentUnlockController', 'display']],

    [['GET', 'POST'], '/tableprn', ['Controllers\PRNTableController', 'display']],
    [['GET'], '/unlockprn', ['Controllers\PRNUnlockController', 'display']],
    [['GET', 'POST'], '/editprn', ['Controllers\EditPRNController', 'display']],

    [['GET', 'POST'], '/createdeposit', ['Controllers\MakeDepositController', 'display']],
    [['GET', 'POST'], '/createrefund', ['Controllers\MakeRefundController', 'display']],
    [['GET', 'POST'], '/disburseprn', ['Controllers\DisburseController', 'display']],
    [['GET', 'POST'], '/employee', ['Controllers\EmployeeController', 'display']],

    [['GET', 'POST'], '/report/{name:POTEmployeeSummary|POTPaymentByEntityCombined|POTPaymentByEntityIndividual|POTPayslips}', ['Controllers\PaymentsReportController', 'display']],
    [['GET', 'POST'], '/report/{name:POTEntityDetails|POTEntitySummary|PrnEntity|RefundEntity|PotEmployeeDetails|POTPRNByEntity|POTRefundByEntity|CompanyListing|EmployeeListing|ReceiptsByEntityCombined|ReceiptsByEntityIndividual}', ['Controllers\ManagersReportController', 'display']],
    ['GET', '/index.php', ['Controllers\Homepage', 'display']],
    ['GET', '/', ['Controllers\Homepage', 'display']],
    [['GET', 'POST'], '/login', ['Controllers\Login', 'show']],
    [['GET', 'POST'], '/changepassword', ['Controllers\PasswordController', 'display']],
    [['GET', 'POST'], '/logout', ['Controllers\Login', 'logout']],
];
